# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
